/* Auto-generated by memtune work_mem distillation. */
#ifndef MEMTUNE_WORKMEM_MODEL_H
#define MEMTUNE_WORKMEM_MODEL_H

#include <stdint.h>

#define MEMTUNE_WORKMEM_FEATURE_SCHEMA "workmem-3bound-features-v1"
#define MEMTUNE_WORKMEM_FEATURE_COUNT 19
#define MEMTUNE_WORKMEM_MODEL_VERSION 2

typedef struct GsAmmDtreeDetail GsAmmDtreeDetail;

typedef enum MemTuneWorkMemFeatureIndex
{
    MEMTUNE_FEATURE_HASH_JOIN_NODES = 0,
    MEMTUNE_FEATURE_SORT_NODES = 1,
    MEMTUNE_FEATURE_AGGREGATE_NODES = 2,
    MEMTUNE_FEATURE_WINDOW_NODES = 3,
    MEMTUNE_FEATURE_MAX_PLAN_ROWS_LOG10 = 4,
    MEMTUNE_FEATURE_MAX_PLAN_WIDTH = 5,
    MEMTUNE_FEATURE_TOTAL_COST = 6,
    MEMTUNE_FEATURE_PARALLEL_WORKERS_PLANNED = 7,
    MEMTUNE_FEATURE_PARALLEL_AWARE_NODES = 8,
    MEMTUNE_FEATURE_ACTIVE_SESSIONS = 9,
    MEMTUNE_FEATURE_CURRENT_SESSION_PRIVATE_MEMORY_MB = 10,
    MEMTUNE_FEATURE_CURRENT_TRANSACTION_AGE_SEC = 11,
    MEMTUNE_FEATURE_SYSTEM_TOTAL_MEMORY_MB = 12,
    MEMTUNE_FEATURE_SYSTEM_AVAILABLE_MEMORY_MB = 13,
    MEMTUNE_FEATURE_MEMORY_PRESSURE_SCORE = 14,
    MEMTUNE_FEATURE_INVOLVED_TABLE_TOTAL_SIZE_MB = 15,
    MEMTUNE_FEATURE_INVOLVED_INDEX_TOTAL_SIZE_MB = 16,
    MEMTUNE_FEATURE_AVERAGE_COLUMN_WIDTH = 17,
    MEMTUNE_FEATURE_TOTAL_COST_LOG1P = 18
} MemTuneWorkMemFeatureIndex;

typedef struct MemTuneWorkMemFeatures
{
    double hash_join_nodes;
    double sort_nodes;
    double aggregate_nodes;
    double window_nodes;
    double max_plan_rows_log10;
    double max_plan_width;
    double total_cost;
    double parallel_workers_planned;
    double parallel_aware_nodes;
    double active_sessions;
    double current_session_private_memory_mb;
    double current_transaction_age_sec;
    double system_total_memory_mb;
    double system_available_memory_mb;
    double memory_pressure_score;
    double involved_table_total_size_mb;
    double involved_index_total_size_mb;
    double average_column_width;
    double total_cost_log1p;
} MemTuneWorkMemFeatures;

typedef struct MemTuneWorkMemBounds
{
    double cache_mb;
    double one_pass_mb;
    double multi_pass_mb;
} MemTuneWorkMemBounds;

typedef struct MemTuneWorkMemPrediction
{
    MemTuneWorkMemBounds bounds;
    int64_t model_version;
    int64_t leaf_id;
} MemTuneWorkMemPrediction;

void memtune_workmem_features_to_array(
    const MemTuneWorkMemFeatures *features,
    double output[MEMTUNE_WORKMEM_FEATURE_COUNT]);

MemTuneWorkMemBounds memtune_predict_workmem_bounds(
    const double features[MEMTUNE_WORKMEM_FEATURE_COUNT]);

MemTuneWorkMemPrediction memtune_predict_workmem_detail(
    const double features[MEMTUNE_WORKMEM_FEATURE_COUNT]);

extern bool GsWorkmemDtreePredictDetail(
    const double features[MEMTUNE_WORKMEM_FEATURE_COUNT], GsAmmDtreeDetail *detail);

#endif /* MEMTUNE_WORKMEM_MODEL_H */
