/* Generated by export_xgb_model_cpp.py. */
#ifndef MEMTUNE_WORKMEM_XGB_V5_MODEL_H
#define MEMTUNE_WORKMEM_XGB_V5_MODEL_H

#include <stdint.h>

#define MEMTUNE_XGB_V5_FEATURE_SCHEMA "workmem-3bound-features-mixed-clean-v5"
#define MEMTUNE_XGB_V5_FEATURE_COUNT 24
#define MEMTUNE_XGB_V5_MODEL_VERSION 5

typedef struct GsAmmDtreeDetail GsAmmDtreeDetail;

typedef enum MemTuneXgbV5FeatureIndex {
    MEMTUNE_XGB_V5_HASH_JOIN_NODES = 0,
    MEMTUNE_XGB_V5_SORT_NODES,
    MEMTUNE_XGB_V5_AGGREGATE_NODES,
    MEMTUNE_XGB_V5_WINDOW_NODES,
    MEMTUNE_XGB_V5_MAX_PLAN_ROWS_LOG10,
    MEMTUNE_XGB_V5_MAX_PLAN_WIDTH,
    MEMTUNE_XGB_V5_TOTAL_COST,
    MEMTUNE_XGB_V5_PARALLEL_WORKERS_PLANNED,
    MEMTUNE_XGB_V5_PARALLEL_AWARE_NODES,
    MEMTUNE_XGB_V5_INVOLVED_TABLE_TOTAL_SIZE_MB,
    MEMTUNE_XGB_V5_INVOLVED_INDEX_TOTAL_SIZE_MB,
    MEMTUNE_XGB_V5_TABLE_COUNT,
    MEMTUNE_XGB_V5_INDEX_TABLE_RATIO,
    MEMTUNE_XGB_V5_TOTAL_COST_LOG1P,
    MEMTUNE_XGB_V5_TABLE_SIZE_LOG1P,
    MEMTUNE_XGB_V5_INDEX_SIZE_LOG1P,
    MEMTUNE_XGB_V5_ROWS_WIDTH_LOG1P,
    MEMTUNE_XGB_V5_PLAN_NODE_COUNT,
    MEMTUNE_XGB_V5_SORT_INPUT_ROWS,
    MEMTUNE_XGB_V5_SORT_TUPLE_WIDTH,
    MEMTUNE_XGB_V5_SORT_INPUT_BYTES,
    MEMTUNE_XGB_V5_SORT_KEY_COUNT,
    MEMTUNE_XGB_V5_SORT_INPUT_ROWS_LOG1P,
    MEMTUNE_XGB_V5_SORT_INPUT_BYTES_LOG1P
} MemTuneXgbV5FeatureIndex;

typedef struct MemTuneWorkMemFeaturesV5 {
    double hash_join_nodes;
    double sort_nodes;
    double aggregate_nodes;
    double window_nodes;
    double max_plan_rows_log10;
    double max_plan_width;
    double total_cost;
    double parallel_workers_planned;
    double parallel_aware_nodes;
    double involved_table_total_size_mb;
    double involved_index_total_size_mb;
    double table_count;
    double index_table_ratio;
    double total_cost_log1p;
    double table_size_log1p;
    double index_size_log1p;
    double rows_width_log1p;
    double plan_node_count;
    double sort_input_rows;
    double sort_tuple_width;
    double sort_input_bytes;
    double sort_key_count;
    double sort_input_rows_log1p;
    double sort_input_bytes_log1p;
} MemTuneWorkMemFeaturesV5;

typedef struct MemTuneXgbV5Prediction {
    double cache_mb;
    double one_pass_mb;
    double multi_pass_mb;
    int64_t model_version;
    int64_t leaf_id;
} MemTuneXgbV5Prediction;

void memtune_xgb_v5_features_to_array(
    const MemTuneWorkMemFeaturesV5 *features,
    double output[MEMTUNE_XGB_V5_FEATURE_COUNT]);

MemTuneXgbV5Prediction memtune_predict_xgb_v5(
    const double features[MEMTUNE_XGB_V5_FEATURE_COUNT]);

extern bool GsWorkmemXgbV5PredictDetail(
    const double features[MEMTUNE_XGB_V5_FEATURE_COUNT], GsAmmDtreeDetail *detail);

#endif /* MEMTUNE_WORKMEM_XGB_V5_MODEL_H */
