/*-------------------------------------------------------------------------
 *
 * kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef KWLIST_D_H
#define KWLIST_D_H

#include "parser/kwlookup.h"

static const char ScanKeywords_kw_string[] =
	"abort\0"
	"absolute\0"
	"access\0"
	"account\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"algorithm\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"app\0"
	"append\0"
	"archive\0"
	"array\0"
	"as\0"
	"asc\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"attribute\0"
	"audit\0"
	"authid\0"
	"authorization\0"
	"auto_increment\0"
	"autoextend\0"
	"automapped\0"
	"backward\0"
	"barrier\0"
	"before\0"
	"begin\0"
	"begin_non_anoyblock\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"binary_double\0"
	"binary_integer\0"
	"bit\0"
	"blanks\0"
	"blob\0"
	"blockchain\0"
	"body\0"
	"boolean\0"
	"both\0"
	"bucketcnt\0"
	"buckets\0"
	"by\0"
	"byteawithoutorder\0"
	"byteawithoutorderwithequal\0"
	"cache\0"
	"call\0"
	"called\0"
	"cancelable\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"change\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"characterset\0"
	"charset\0"
	"check\0"
	"checkpoint\0"
	"class\0"
	"clean\0"
	"client\0"
	"client_master_key\0"
	"client_master_keys\0"
	"clob\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"column_encryption_key\0"
	"column_encryption_keys\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compact\0"
	"compatible_illegal_chars\0"
	"complete\0"
	"completion\0"
	"compress\0"
	"concurrently\0"
	"condition\0"
	"configuration\0"
	"connect\0"
	"connection\0"
	"constant\0"
	"constraint\0"
	"constraints\0"
	"content\0"
	"continue\0"
	"contview\0"
	"conversion\0"
	"convert\0"
	"coordinator\0"
	"coordinators\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csn\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"datafile\0"
	"datanode\0"
	"datanodes\0"
	"datatype_cl\0"
	"date\0"
	"date_format\0"
	"day\0"
	"day_hour\0"
	"day_minute\0"
	"day_second\0"
	"dbcompatibility\0"
	"deallocate\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"decode\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"delta\0"
	"deltamerge\0"
	"desc\0"
	"deterministic\0"
	"dictionary\0"
	"direct\0"
	"directory\0"
	"disable\0"
	"discard\0"
	"disconnect\0"
	"distinct\0"
	"distribute\0"
	"distribution\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"dumpfile\0"
	"duplicate\0"
	"each\0"
	"elastic\0"
	"else\0"
	"enable\0"
	"enclosed\0"
	"encoding\0"
	"encrypted\0"
	"encrypted_value\0"
	"encryption\0"
	"encryption_type\0"
	"end\0"
	"ends\0"
	"enforced\0"
	"enum\0"
	"eol\0"
	"errors\0"
	"escape\0"
	"escaped\0"
	"escaping\0"
	"event\0"
	"events\0"
	"every\0"
	"except\0"
	"exchange\0"
	"exclude\0"
	"excluded\0"
	"excluding\0"
	"exclusive\0"
	"execute\0"
	"exists\0"
	"expired\0"
	"explain\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fast\0"
	"features\0"
	"fenced\0"
	"fetch\0"
	"fields\0"
	"fileheader\0"
	"fill_missing_fields\0"
	"filler\0"
	"filter\0"
	"first\0"
	"fixed\0"
	"float\0"
	"following\0"
	"follows\0"
	"for\0"
	"force\0"
	"foreign\0"
	"formatter\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"function\0"
	"functions\0"
	"generated\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"grouping\0"
	"groupparent\0"
	"handler\0"
	"having\0"
	"hdfsdirectory\0"
	"header\0"
	"hold\0"
	"hour\0"
	"hour_minute\0"
	"hour_second\0"
	"identified\0"
	"identity\0"
	"if\0"
	"ignore\0"
	"ignore_extra_data\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"incremental\0"
	"index\0"
	"indexes\0"
	"infile\0"
	"inherit\0"
	"inherits\0"
	"initial\0"
	"initially\0"
	"initrans\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"internal\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invisible\0"
	"invoker\0"
	"ip\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"join\0"
	"key\0"
	"key_path\0"
	"key_store\0"
	"kill\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lc_collate\0"
	"lc_ctype\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"less\0"
	"level\0"
	"like\0"
	"limit\0"
	"lines\0"
	"list\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"log\0"
	"logging\0"
	"login_any\0"
	"login_failure\0"
	"login_success\0"
	"logout\0"
	"loop\0"
	"mapping\0"
	"masking\0"
	"master\0"
	"match\0"
	"matched\0"
	"materialized\0"
	"maxextents\0"
	"maxsize\0"
	"maxtrans\0"
	"maxvalue\0"
	"merge\0"
	"minextents\0"
	"minus\0"
	"minute\0"
	"minute_second\0"
	"minvalue\0"
	"mode\0"
	"model\0"
	"modify\0"
	"month\0"
	"move\0"
	"movement\0"
	"name\0"
	"names\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"next\0"
	"no\0"
	"nocompress\0"
	"nocycle\0"
	"node\0"
	"nologging\0"
	"nomaxvalue\0"
	"nominvalue\0"
	"none\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"nowait\0"
	"null\0"
	"nullcols\0"
	"nullif\0"
	"nulls\0"
	"number\0"
	"numeric\0"
	"numstr\0"
	"nvarchar\0"
	"nvarchar2\0"
	"nvl\0"
	"object\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"on\0"
	"only\0"
	"operator\0"
	"optimization\0"
	"option\0"
	"optionally\0"
	"options\0"
	"or\0"
	"order\0"
	"out\0"
	"outer\0"
	"outfile\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"owned\0"
	"owner\0"
	"package\0"
	"packages\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"partitions\0"
	"passing\0"
	"password\0"
	"pctfree\0"
	"per\0"
	"percent\0"
	"performance\0"
	"perm\0"
	"placing\0"
	"plan\0"
	"plans\0"
	"policy\0"
	"pool\0"
	"position\0"
	"precedes\0"
	"preceding\0"
	"precision\0"
	"predict\0"
	"preferred\0"
	"prefix\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"priorer\0"
	"private\0"
	"privilege\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"profile\0"
	"publication\0"
	"publish\0"
	"purge\0"
	"query\0"
	"quote\0"
	"randomized\0"
	"range\0"
	"ratio\0"
	"raw\0"
	"read\0"
	"real\0"
	"reassign\0"
	"rebuild\0"
	"recheck\0"
	"recursive\0"
	"recyclebin\0"
	"redisanyvalue\0"
	"ref\0"
	"references\0"
	"refresh\0"
	"reindex\0"
	"reject\0"
	"relative\0"
	"release\0"
	"reloptions\0"
	"remote\0"
	"remove\0"
	"rename\0"
	"repeat\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"resize\0"
	"resource\0"
	"restart\0"
	"restrict\0"
	"return\0"
	"returning\0"
	"returns\0"
	"reuse\0"
	"revoke\0"
	"right\0"
	"role\0"
	"roles\0"
	"rollback\0"
	"rollup\0"
	"rotation\0"
	"row\0"
	"rownum\0"
	"rows\0"
	"rowtype\0"
	"rule\0"
	"sample\0"
	"savepoint\0"
	"schedule\0"
	"schema\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"separator\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"share\0"
	"shippable\0"
	"show\0"
	"shrink\0"
	"shutdown\0"
	"siblings\0"
	"similar\0"
	"simple\0"
	"size\0"
	"skip\0"
	"slave\0"
	"slice\0"
	"smalldatetime\0"
	"smalldatetime_format\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"source\0"
	"space\0"
	"spill\0"
	"split\0"
	"sql\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"starting\0"
	"starts\0"
	"statement\0"
	"statement_id\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"store\0"
	"stored\0"
	"stratify\0"
	"stream\0"
	"strict\0"
	"strip\0"
	"subpartition\0"
	"subpartitions\0"
	"subscription\0"
	"substring\0"
	"symmetric\0"
	"synonym\0"
	"sys_refcursor\0"
	"sysdate\0"
	"sysid\0"
	"system\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"target\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"terminated\0"
	"text\0"
	"than\0"
	"then\0"
	"time\0"
	"time_format\0"
	"timecapsule\0"
	"timestamp\0"
	"timestamp_format\0"
	"timestampdiff\0"
	"tinyint\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"tsfield\0"
	"tstag\0"
	"tstime\0"
	"type\0"
	"types\0"
	"unbounded\0"
	"uncommitted\0"
	"unencrypted\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlimited\0"
	"unlisten\0"
	"unlock\0"
	"unlogged\0"
	"until\0"
	"unusable\0"
	"update\0"
	"use\0"
	"useeof\0"
	"user\0"
	"using\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validation\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"varchar2\0"
	"variables\0"
	"variadic\0"
	"varying\0"
	"vcgroup\0"
	"verbose\0"
	"verify\0"
	"version\0"
	"view\0"
	"visible\0"
	"volatile\0"
	"wait\0"
	"warnings\0"
	"weak\0"
	"when\0"
	"where\0"
	"while\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"workload\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"year\0"
	"year_month\0"
	"yes\0"
	"zone";

static const uint16 ScanKeywords_kw_offsets[] = {
	0,
	6,
	15,
	22,
	30,
	37,
	41,
	47,
	53,
	63,
	73,
	77,
	82,
	88,
	95,
	103,
	111,
	115,
	119,
	123,
	130,
	138,
	144,
	147,
	151,
	161,
	172,
	183,
	186,
	196,
	202,
	209,
	223,
	238,
	249,
	260,
	269,
	277,
	284,
	290,
	310,
	318,
	325,
	332,
	346,
	361,
	365,
	372,
	377,
	388,
	393,
	401,
	406,
	416,
	424,
	427,
	445,
	472,
	478,
	483,
	490,
	501,
	509,
	518,
	523,
	528,
	536,
	542,
	549,
	554,
	564,
	580,
	593,
	601,
	607,
	618,
	624,
	630,
	637,
	655,
	674,
	679,
	685,
	693,
	702,
	710,
	720,
	727,
	749,
	772,
	780,
	788,
	797,
	804,
	814,
	822,
	847,
	856,
	867,
	876,
	889,
	899,
	913,
	921,
	932,
	941,
	952,
	964,
	972,
	981,
	990,
	1001,
	1009,
	1021,
	1034,
	1039,
	1044,
	1051,
	1057,
	1061,
	1065,
	1070,
	1078,
	1094,
	1107,
	1120,
	1135,
	1148,
	1166,
	1179,
	1186,
	1192,
	1197,
	1206,
	1215,
	1224,
	1234,
	1246,
	1251,
	1263,
	1267,
	1276,
	1287,
	1298,
	1314,
	1325,
	1329,
	1337,
	1345,
	1352,
	1360,
	1369,
	1380,
	1389,
	1397,
	1404,
	1414,
	1425,
	1431,
	1442,
	1447,
	1461,
	1472,
	1479,
	1489,
	1497,
	1505,
	1516,
	1525,
	1536,
	1549,
	1552,
	1561,
	1568,
	1575,
	1580,
	1589,
	1599,
	1604,
	1612,
	1617,
	1624,
	1633,
	1642,
	1652,
	1668,
	1679,
	1695,
	1699,
	1704,
	1713,
	1718,
	1722,
	1729,
	1736,
	1744,
	1753,
	1759,
	1766,
	1772,
	1779,
	1788,
	1796,
	1805,
	1815,
	1825,
	1833,
	1840,
	1848,
	1856,
	1866,
	1875,
	1883,
	1889,
	1896,
	1901,
	1910,
	1917,
	1923,
	1930,
	1941,
	1961,
	1968,
	1975,
	1981,
	1987,
	1993,
	2003,
	2011,
	2015,
	2021,
	2029,
	2039,
	2047,
	2054,
	2059,
	2064,
	2073,
	2083,
	2093,
	2100,
	2106,
	2114,
	2123,
	2129,
	2138,
	2150,
	2158,
	2165,
	2179,
	2186,
	2191,
	2196,
	2208,
	2220,
	2231,
	2240,
	2243,
	2250,
	2268,
	2274,
	2284,
	2294,
	2303,
	2306,
	2314,
	2324,
	2334,
	2346,
	2352,
	2360,
	2367,
	2375,
	2384,
	2392,
	2402,
	2411,
	2418,
	2424,
	2430,
	2436,
	2448,
	2455,
	2463,
	2467,
	2475,
	2484,
	2494,
	2503,
	2508,
	2518,
	2526,
	2529,
	2532,
	2539,
	2549,
	2554,
	2558,
	2567,
	2577,
	2582,
	2588,
	2597,
	2603,
	2608,
	2619,
	2628,
	2636,
	2646,
	2652,
	2657,
	2662,
	2668,
	2673,
	2679,
	2685,
	2690,
	2697,
	2702,
	2708,
	2718,
	2733,
	2742,
	2747,
	2754,
	2758,
	2766,
	2776,
	2790,
	2804,
	2811,
	2816,
	2824,
	2832,
	2839,
	2845,
	2853,
	2866,
	2877,
	2885,
	2894,
	2903,
	2909,
	2920,
	2926,
	2933,
	2947,
	2956,
	2961,
	2967,
	2974,
	2980,
	2985,
	2994,
	2999,
	3005,
	3014,
	3022,
	3028,
	3033,
	3036,
	3047,
	3055,
	3060,
	3070,
	3081,
	3092,
	3097,
	3101,
	3109,
	3116,
	3124,
	3131,
	3136,
	3145,
	3152,
	3158,
	3165,
	3173,
	3180,
	3189,
	3199,
	3203,
	3210,
	3213,
	3217,
	3224,
	3229,
	3232,
	3237,
	3246,
	3259,
	3266,
	3277,
	3285,
	3288,
	3294,
	3298,
	3304,
	3312,
	3317,
	3326,
	3334,
	3340,
	3346,
	3354,
	3363,
	3370,
	3378,
	3388,
	3399,
	3407,
	3416,
	3424,
	3428,
	3436,
	3448,
	3453,
	3461,
	3466,
	3472,
	3479,
	3484,
	3493,
	3502,
	3512,
	3522,
	3530,
	3540,
	3547,
	3555,
	3564,
	3573,
	3581,
	3587,
	3595,
	3603,
	3613,
	3624,
	3635,
	3645,
	3653,
	3665,
	3673,
	3679,
	3685,
	3691,
	3702,
	3708,
	3714,
	3718,
	3723,
	3728,
	3737,
	3745,
	3753,
	3763,
	3774,
	3788,
	3792,
	3803,
	3811,
	3819,
	3826,
	3835,
	3843,
	3854,
	3861,
	3868,
	3875,
	3882,
	3893,
	3901,
	3909,
	3915,
	3922,
	3931,
	3939,
	3948,
	3955,
	3965,
	3973,
	3979,
	3986,
	3992,
	3997,
	4003,
	4012,
	4019,
	4028,
	4032,
	4039,
	4044,
	4052,
	4057,
	4064,
	4074,
	4083,
	4090,
	4097,
	4104,
	4111,
	4120,
	4127,
	4137,
	4146,
	4156,
	4169,
	4176,
	4184,
	4197,
	4201,
	4207,
	4212,
	4218,
	4228,
	4233,
	4240,
	4249,
	4258,
	4266,
	4273,
	4278,
	4283,
	4289,
	4295,
	4309,
	4330,
	4339,
	4348,
	4353,
	4360,
	4366,
	4372,
	4378,
	4382,
	4389,
	4400,
	4406,
	4415,
	4422,
	4432,
	4445,
	4456,
	4462,
	4469,
	4477,
	4483,
	4490,
	4499,
	4506,
	4513,
	4519,
	4532,
	4546,
	4559,
	4569,
	4579,
	4587,
	4601,
	4609,
	4615,
	4622,
	4628,
	4635,
	4647,
	4658,
	4665,
	4670,
	4679,
	4689,
	4700,
	4705,
	4710,
	4715,
	4720,
	4732,
	4744,
	4754,
	4771,
	4785,
	4793,
	4796,
	4805,
	4817,
	4827,
	4833,
	4841,
	4846,
	4851,
	4860,
	4868,
	4876,
	4882,
	4889,
	4894,
	4900,
	4910,
	4922,
	4934,
	4940,
	4947,
	4955,
	4965,
	4974,
	4981,
	4990,
	4996,
	5005,
	5012,
	5016,
	5023,
	5028,
	5034,
	5041,
	5047,
	5056,
	5067,
	5077,
	5083,
	5090,
	5098,
	5107,
	5117,
	5126,
	5134,
	5142,
	5150,
	5157,
	5165,
	5170,
	5178,
	5187,
	5192,
	5201,
	5206,
	5211,
	5217,
	5223,
	5234,
	5241,
	5246,
	5253,
	5261,
	5266,
	5275,
	5283,
	5289,
	5293,
	5307,
	5317,
	5328,
	5338,
	5348,
	5357,
	5363,
	5371,
	5384,
	5389,
	5400,
	5404,
};

#define SCANKEYWORDS_NUM_KEYWORDS 661

static int
ScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1323] = {
		-310,  -150,  -190,  570,   259,   -262,  32767, 436,
		32767, 183,   0,     487,   -505,  32767, 32767, 32767,
		0,     32767, 122,   494,   302,   32767, 0,     32767,
		-304,  32767, 32767, 32767, 32767, 32767, 32767, 32767,
		32767, 32767, 32767, 32767, 471,   653,   0,     32767,
		32767, -504,  32767, 32767, 32767, 32767, 445,   522,
		32767, 32767, 32767, 99,    0,     -9,    67,    328,
		398,   32767, 32767, 32767, -25,   32767, 32767, 32767,
		32767, 460,   32767, 32767, 101,   -256,  32767, -214,
		286,   520,   -55,   32767, -418,  706,   32767, 550,
		145,   0,     308,   78,    -247,  32767, 32767, 32767,
		-1018, 175,   98,    -144,  32767, 32767, 32767, 219,
		98,    -104,  0,     32767, 200,   76,    32767, 649,
		0,     317,   32767, 32767, 278,   32767, 303,   32767,
		239,   32767, -470,  32767, 58,    32767, 581,   32767,
		429,   32767, 32767, 314,   32767, 625,   582,   5,
		0,     811,   32767, 416,   32767, 32767, 896,   173,
		165,   570,   582,   32767, 809,   227,   -175,  32767,
		898,   -23,   349,   32767, -162,  32767, 325,   32767,
		474,   0,     41,    32767, 32767, -398,  32767, 527,
		32767, 250,   403,   32767, 32767, -383,  32767, 149,
		-30,   15,    -208,  32767, 677,   32767, -154,  32767,
		32767, 32767, 562,   -209,  32767, 538,   3,     32767,
		233,   32767, 288,   32767, 0,     239,   32767, 0,
		32767, -175,  32767, 32767, 32767, 32767, 32767, 32767,
		32767, 32767, 484,   0,     32767, 429,   -53,   452,
		261,   0,     32767, 32767, 32767, 0,     32767, -114,
		0,     0,     0,     32767, 307,   132,   1024,  1349,
		32767, 726,   -1174, -571,  90,    0,     32767, -292,
		32767, -353,  -242,  32767, 32767, 96,    -132,  32767,
		102,   724,   90,    170,   32767, 32767, 232,   473,
		32767, 32767, 298,   32767, 324,   86,    -49,   115,
		32767, 32767, 524,   32767, 32767, 0,     32767, 32767,
		32767, -310,  12,    32767, 541,   32767, 66,    32767,
		-93,   728,   1487,  121,   318,   32767, 32767, 539,
		350,   32767, 123,   425,   -326,  32767, 32767, 32767,
		32767, -348,  32767, 0,     32767, -411,  657,   0,
		32767, 301,   412,   0,     209,   32767, 32767, 180,
		-1094, 32767, 32767, -128,  32767, 244,   64,    32767,
		593,   0,     177,   32767, 397,   32767, 0,     2,
		32767, 0,     -902,  616,   396,   -161,  107,   332,
		471,   32767, 32767, 32767, 32767, 32767, -488,  1552,
		-165,  -267,  0,     77,    34,    240,   32767, 0,
		-86,   32767, 0,     604,   -379,  262,   0,     255,
		361,   32767, 32767, 178,   32767, 584,   252,   32767,
		582,   -438,  0,     32767, 32767, 509,   -39,   32767,
		32767, 780,   32767, 0,     32767, 0,     505,   452,
		32767, 0,     428,   32767, 106,   0,     32767, 0,
		32767, 32767, 32767, 0,     1389,  32767, 32767, -171,
		-328,  -299,  90,    32767, 19,    101,   317,   32767,
		0,     534,   48,    177,   256,   228,   295,   609,
		32767, 73,    32767, -37,   0,     205,   -116,  456,
		32767, 521,   32767, 194,   32767, 32767, 32767, -194,
		32767, 0,     1738,  -358,  0,     32767, 32767, 32767,
		32767, 32767, 32767, 32767, 32767, -83,   32767, 135,
		-24,   990,   302,   32767, 0,     432,   194,   0,
		0,     -179,  32767, 399,   396,   0,     0,     32767,
		32767, 466,   -269,  -402,  1543,  32767, 32767, 0,
		525,   32767, 336,   32767, 495,   660,   32767, -697,
		32767, 32767, 278,   251,   325,   243,   0,     286,
		32767, 32767, 32767, 0,     426,   32767, 32767, 308,
		32767, 624,   0,     -382,  193,   32767, 32767, 32767,
		32767, 613,   380,   32767, 32767, 1395,  0,     36,
		207,   32767, 351,   32767, -90,   97,    32767, 32767,
		32767, -521,  -51,   32767, 32767, 32767, 32767, 0,
		-355,  346,   0,     324,   19,    32767, -277,  649,
		0,     -221,  32767, -66,   1001,  -272,  32767, 213,
		325,   32767, 32767, 32767, 0,     0,     611,   531,
		307,   128,   32767, 321,   440,   -465,  32767, 32767,
		382,   -205,  231,   32767, 32767, 32767, 580,   404,
		0,     256,   339,   -123,  432,   1004,  32767, 32767,
		32767, 0,     32767, -90,   266,   812,   0,     455,
		-67,   18,    0,     0,     156,   32767, 283,   0,
		685,   0,     0,     0,     32767, 32767, 216,   939,
		32767, 631,   53,    103,   0,     854,   359,   32767,
		32767, 223,   -351,  32767, 634,   146,   32767, 32767,
		0,     25,    -863,  50,    255,   -51,   143,   -448,
		32767, -77,   610,   -109,  256,   484,   32767, -176,
		448,   277,   32767, -16,   32767, 0,     32767, 32767,
		248,   279,   -37,   -181,  374,   291,   521,   32767,
		-18,   32767, 70,    24,    32767, 865,   750,   465,
		589,   32767, -38,   299,   32767, 16,    0,     0,
		195,   32767, 390,   242,   352,   32767, 32767, 150,
		409,   55,    1461,  851,   277,   0,     -415,  1592,
		32767, 32767, -461,  32767, -1508, 0,     0,     32767,
		32767, -536,  221,   755,   32767, 32767, 49,    32767,
		348,   0,     32767, 32767, 0,     850,   0,     886,
		517,   241,   0,     0,     32767, 32767, 32767, 0,
		0,     -74,   32767, 32767, 32767, 32767, -568,  32767,
		-558,  32767, -183,  634,   32767, 422,   296,   32767,
		32767, 32767, 243,   32767, 599,   0,     32767, 0,
		221,   32767, 370,   -71,   357,   32767, 32767, 32767,
		451,   105,   459,   701,   32767, 160,   326,   0,
		59,    32767, 697,   385,   665,   204,   32767, 164,
		32767, 165,   0,     -1,    705,   335,   32767, 499,
		32767, 2,     32767, 32767, 32767, 32767, 584,   0,
		792,   27,    32767, 0,     0,     32767, 32767, 253,
		32767, 32767, 32767, 612,   -196,  -443,  559,   0,
		113,   32767, 32767, 32767, -166,  32767, 738,   100,
		26,    107,   65,    74,    131,   586,   32767, 208,
		178,   32767, 824,   497,   0,     1041,  46,    417,
		32767, 32767, 0,     32767, 0,     32767, 79,    0,
		32767, 581,   -935,  32767, 520,   61,    32767, 619,
		298,   0,     335,   32767, 32767, 125,   225,   32767,
		68,    -925,  32767, -211,  195,   512,   -439,  464,
		32767, 627,   32767, 557,   565,   22,    -7,    107,
		0,     -519,  0,     66,    32767, -273,  -1074, 0,
		1131,  32767, 809,   20,    134,   47,    0,     32767,
		32767, 144,   -137,  32767, 10,    127,   32767, 32767,
		797,   32767, 712,   -633,  32767, 32767, 32767, 492,
		32767, 0,     338,   32767, 0,     32767, 32767, -7,
		32767, 38,    0,     277,   637,   -280,  32767, 0,
		87,    420,   615,   -339,  32767, 32767, 263,   32767,
		32767, 0,     0,     32767, 32767, 430,   0,     -260,
		32767, 32767, 32767, 0,     47,    32767, 32767, 836,
		32767, 496,   554,   32767, -43,   595,   32767, 59,
		305,   32767, 32767, 32767, 32767, 32767, 32767, 32767,
		0,     0,     32767, 641,   0,     32767, -114,  32767,
		38,    -218,  995,   0,     1152,  133,   597,   -488,
		381,   -821,  32767, 234,   32767, -427,  637,   247,
		32767, 299,   32767, 0,     -818,  32767, 32767, 599,
		0,     281,   -395,  613,   0,     32767, 528,   447,
		-171,  460,   242,   219,   32767, 32767, 791,   0,
		546,   211,   0,     272,   296,   282,   32767, 32767,
		32767, 32767, 8,     419,   407,   0,     0,     32767,
		390,   663,   -349,  0,     1463,  32767, 0,     0,
		0,     0,     305,   310,   346,   -932,  0,     393,
		32767, 32767, 32767, 479,   257,   419,   32767, 187,
		32767, 32767, 246,   236,   -319,  32767, 32767, 406,
		32767, 121,   32767, 32767, 475,   32767, 32767, 32767,
		32767, 590,   -194,  32767, 32767, 625,   -44,   32767,
		366,   32767, 32767, 32767, 32767, -489,  32767, 32767,
		32767, 32767, -494,  32767, 32767, 214,   81,    -304,
		0,     32767, 62,    32767, 531,   0,     32767, 528,
		576,   32767, 0,     -338,  32767, 204,   0,     56,
		8,     0,     32767, -119,  0,     32767, 120,   -283,
		-510,  32767, -537,  607,   32767, 32767, 380,   32767,
		32767, 489,   0,     0,     60,    321,   32767, 32767,
		257,   32767, 0,     32767, 32767, 1117,  0,     640,
		14,    0,     -457,  176,   32767, 32767, 32767, -377,
		32767, 268,   -10,   655,   362,   158,   32767, 461,
		0,     -520,  32767, -371,  32767, 282,   10,    208,
		14,    0,     0,     0,     583,   -144,  242,   -459,
		428,   522,   317,   32767, -466,  32767, 32767, 653,
		-609,  -169,  0,     -324,  32767, 543,   388,   32767,
		184,   -253,  0,     206,   32767, 710,   32767, -54,
		-217,  398,   32767, 32767, 229,   319,   0,     32767,
		32767, 32767, 32767, 82,    0,     -345,  32767, 32767,
		129,   0,     32767, 794,   32767, 32767, 361,   0,
		0,     0,     32767, 0,     32767, 222,   0,     629,
		657,   32767, 32767, 235,   0,     32767, 32767, 32767,
		0,     0,     272,   32767, 236,   129,   337,   32767,
		491,   434,   0,     272,   32767, 32767, 32767, 855,
		32767, 275,   256,   444,   510,   0,     22,    27,
		310,   542,   0,     191,   -203,  -164,  220,   32767,
		-337,  32767, 397,   93,    32767, 0,     -873,  32767,
		32767, 32767, 32767, 245,   0,     32767, -573,  0,
		489,   0,     -211,  0,     4,     32767, 32767, 175,
		32767, 32767, -8,    32767, 0,     32767, 819,   0,
		340,   32767, 196,   392,   32767, 32767, 0,     32767,
		32767, 32767, 32767, 44,    0,     1038,  656,   32767,
		32767, 863,   32767, 0,     -454,  719,   0,     0,
		32767, 32767, 32767, 475,   1115,  0,     0,     32767,
		32767, 264,   248,   32767, 163,   0,     32767, 0,
		0,     262,   32767, 946,   9,     1109,  32767, 0,
		152,   342,   32767
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 4;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 127 + c;
	}
	return h[a % 1323] + h[b % 1323];
}

const ScanKeywordList ScanKeywords = {
	ScanKeywords_kw_string,
	ScanKeywords_kw_offsets,
	ScanKeywords_hash_func,
	SCANKEYWORDS_NUM_KEYWORDS,
	26
};

#endif							/* KWLIST_D_H */
