#!/usr/bin/env python3
"""Export the portable XGBoost JSON artifact as a static C++ predictor.

The generated predictor intentionally uses only the numerical tree arrays
needed by this model.  It does not link against libxgboost, so the output can
be compiled into an openGauss backend with a different XGBoost version.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Any


FEATURE_NAMES = (
    "hash_join_nodes", "sort_nodes", "aggregate_nodes", "window_nodes",
    "max_plan_rows_log10", "max_plan_width", "total_cost",
    "parallel_workers_planned", "parallel_aware_nodes",
    "involved_table_total_size_mb", "involved_index_total_size_mb",
    "table_count", "index_table_ratio", "total_cost_log1p",
    "table_size_log1p", "index_size_log1p", "rows_width_log1p",
    "plan_node_count", "sort_input_rows", "sort_tuple_width",
    "sort_input_bytes", "sort_key_count", "sort_input_rows_log1p",
    "sort_input_bytes_log1p",
)


def number(value: Any) -> str:
    value = float(value)
    if not math.isfinite(value):
        raise ValueError(f"non-finite model value: {value!r}")
    return format(value, ".17g")


def c_array(values: list[Any], formatter=number, width: int = 8) -> str:
    chunks = [formatter(value) for value in values]
    lines = []
    for start in range(0, len(chunks), width):
        lines.append("    " + ", ".join(chunks[start:start + width]) + ",")
    return "\n".join(lines)


def model_arrays(model: dict[str, Any]) -> dict[str, list[Any]]:
    trees = model["learner"]["gradient_booster"]["model"]["trees"]
    offsets = [0]
    arrays: dict[str, list[Any]] = {
        "left": [], "right": [], "split_index": [], "split_condition": [],
        "default_left": [], "leaf_weight": [],
    }
    for tree in trees:
        weights = tree["base_weights"]
        arrays["left"].extend(int(value) for value in tree["left_children"])
        arrays["right"].extend(int(value) for value in tree["right_children"])
        arrays["split_index"].extend(int(value) for value in tree["split_indices"])
        arrays["split_condition"].extend(float(value) for value in tree["split_conditions"])
        arrays["default_left"].extend(int(value) for value in tree["default_left"])
        arrays["leaf_weight"].extend(float(value) for value in weights)
        offsets.append(len(arrays["left"]))
    arrays["offsets"] = offsets
    arrays["tree_count"] = [len(trees)]
    return arrays


def emit_header(path: Path, model_version: int) -> None:
    content = """/* Generated by export_xgb_model_cpp.py. */
#ifndef MEMTUNE_WORKMEM_XGB_V4_MODEL_H
#define MEMTUNE_WORKMEM_XGB_V4_MODEL_H

#include <stdint.h>

#define MEMTUNE_XGB_V4_FEATURE_SCHEMA "workmem-3bound-features-mixed-clean-v4"
#define MEMTUNE_XGB_V4_FEATURE_COUNT 24
#define MEMTUNE_XGB_V4_MODEL_VERSION 4

typedef struct GsAmmDtreeDetail GsAmmDtreeDetail;

typedef enum MemTuneXgbV4FeatureIndex {
    MEMTUNE_XGB_V4_HASH_JOIN_NODES = 0,
    MEMTUNE_XGB_V4_SORT_NODES,
    MEMTUNE_XGB_V4_AGGREGATE_NODES,
    MEMTUNE_XGB_V4_WINDOW_NODES,
    MEMTUNE_XGB_V4_MAX_PLAN_ROWS_LOG10,
    MEMTUNE_XGB_V4_MAX_PLAN_WIDTH,
    MEMTUNE_XGB_V4_TOTAL_COST,
    MEMTUNE_XGB_V4_PARALLEL_WORKERS_PLANNED,
    MEMTUNE_XGB_V4_PARALLEL_AWARE_NODES,
    MEMTUNE_XGB_V4_INVOLVED_TABLE_TOTAL_SIZE_MB,
    MEMTUNE_XGB_V4_INVOLVED_INDEX_TOTAL_SIZE_MB,
    MEMTUNE_XGB_V4_TABLE_COUNT,
    MEMTUNE_XGB_V4_INDEX_TABLE_RATIO,
    MEMTUNE_XGB_V4_TOTAL_COST_LOG1P,
    MEMTUNE_XGB_V4_TABLE_SIZE_LOG1P,
    MEMTUNE_XGB_V4_INDEX_SIZE_LOG1P,
    MEMTUNE_XGB_V4_ROWS_WIDTH_LOG1P,
    MEMTUNE_XGB_V4_PLAN_NODE_COUNT,
    MEMTUNE_XGB_V4_SORT_INPUT_ROWS,
    MEMTUNE_XGB_V4_SORT_TUPLE_WIDTH,
    MEMTUNE_XGB_V4_SORT_INPUT_BYTES,
    MEMTUNE_XGB_V4_SORT_KEY_COUNT,
    MEMTUNE_XGB_V4_SORT_INPUT_ROWS_LOG1P,
    MEMTUNE_XGB_V4_SORT_INPUT_BYTES_LOG1P
} MemTuneXgbV4FeatureIndex;

typedef struct MemTuneWorkMemFeaturesV4 {
    double hash_join_nodes;
    double sort_nodes;
    double aggregate_nodes;
    double window_nodes;
    double max_plan_rows_log10;
    double max_plan_width;
    double total_cost;
    double parallel_workers_planned;
    double parallel_aware_nodes;
    double involved_table_total_size_mb;
    double involved_index_total_size_mb;
    double table_count;
    double index_table_ratio;
    double total_cost_log1p;
    double table_size_log1p;
    double index_size_log1p;
    double rows_width_log1p;
    double plan_node_count;
    double sort_input_rows;
    double sort_tuple_width;
    double sort_input_bytes;
    double sort_key_count;
    double sort_input_rows_log1p;
    double sort_input_bytes_log1p;
} MemTuneWorkMemFeaturesV4;

typedef struct MemTuneXgbV4Prediction {
    double cache_mb;
    double one_pass_mb;
    double multi_pass_mb;
    int64_t model_version;
    int64_t leaf_id;
} MemTuneXgbV4Prediction;

void memtune_xgb_v4_features_to_array(
    const MemTuneWorkMemFeaturesV4 *features,
    double output[MEMTUNE_XGB_V4_FEATURE_COUNT]);

MemTuneXgbV4Prediction memtune_predict_xgb_v4(
    const double features[MEMTUNE_XGB_V4_FEATURE_COUNT]);

extern bool GsWorkmemXgbV4PredictDetail(
    const double features[MEMTUNE_XGB_V4_FEATURE_COUNT], GsAmmDtreeDetail *detail);

#endif /* MEMTUNE_WORKMEM_XGB_V4_MODEL_H */
"""
    content = content.replace("V4", f"V{model_version}")
    content = content.replace("v4", f"v{model_version}")
    content = content.replace(
        f"#define MEMTUNE_XGB_V{model_version}_MODEL_VERSION 4",
        f"#define MEMTUNE_XGB_V{model_version}_MODEL_VERSION {model_version}",
    )
    path.write_text(content, encoding="ascii")


def emit_cpp(path: Path, cache: dict[str, Any], one: dict[str, Any], config: dict[str, Any],
             model_version: int) -> None:
    cache_arrays = model_arrays(cache)
    one_arrays = model_arrays(one)
    imputation = [float(config.get("feature_imputation", {}).get(name, 0.0)) for name in FEATURE_NAMES]

    def emit_model(prefix: str, model: dict[str, Any], arrays: dict[str, list[Any]]) -> str:
        nodes = len(arrays["left"])
        trees = arrays["tree_count"][0]
        return f"""static const uint32_t {prefix}_tree_offsets[{trees + 1}] = {{
{c_array(arrays['offsets'], lambda value: str(int(value)), 12)}
}};
static const int32_t {prefix}_left[{nodes}] = {{
{c_array(arrays['left'], lambda value: str(int(value)))}
}};
static const int32_t {prefix}_right[{nodes}] = {{
{c_array(arrays['right'], lambda value: str(int(value)))}
}};
static const int32_t {prefix}_split_index[{nodes}] = {{
{c_array(arrays['split_index'], lambda value: str(int(value)))}
}};
static const double {prefix}_split_condition[{nodes}] = {{
{c_array(arrays['split_condition'])}
}};
static const uint8_t {prefix}_default_left[{nodes}] = {{
{c_array(arrays['default_left'], lambda value: str(int(value)))}
}};
static const double {prefix}_leaf_weight[{nodes}] = {{
{c_array(arrays['leaf_weight'])}
}};
static const double {prefix}_base_score = {number(model['learner']['learner_model_param']['base_score'])};
"""

    source = f"""/* Generated by export_xgb_model_cpp.py; do not edit manually. */
#include "postgres.h"
#include "knl/knl_variable.h"
#include "storage/buf/buf_internals.h"
#include "utils/workmem_xgb_v4_model.h"
#include "storage/gs_amm.h"
#include <math.h>
#include <string.h>

#define MEMTUNE_XGB_V4_MIN_MB 0.0625
#define MEMTUNE_XGB_V4_MULTI_PASS_DELTA_MB (1.0 / 1024.0)
#define MEMTUNE_FNV_OFFSET 1469598103934665603ULL
#define MEMTUNE_FNV_PRIME 1099511628211ULL

{emit_model('memtune_xgb_v4_cache', cache, cache_arrays)}
{emit_model('memtune_xgb_v4_one', one, one_arrays)}

static const double memtune_xgb_v4_imputation[MEMTUNE_XGB_V4_FEATURE_COUNT] = {{
{c_array(imputation, number, 6)}
}};

static double memtune_xgb_v4_tree(const double *features, const uint32_t *offsets,
    const int32_t *left, const int32_t *right, const int32_t *split_index,
    const double *split_condition, const uint8_t *default_left,
    const double *leaf_weight, uint32_t tree)
{{
    int32_t node = 0;
    uint32_t base = offsets[tree];
    uint32_t end = offsets[tree + 1];
    while (node >= 0 && base + (uint32_t)node < end) {{
        uint32_t index = base + (uint32_t)node;
        if (left[index] < 0 && right[index] < 0)
            return leaf_weight[index];
        int32_t feature = split_index[index];
        double value = (feature >= 0 && feature < MEMTUNE_XGB_V4_FEATURE_COUNT) ?
            features[feature] : NAN;
        if (!isfinite(value))
            node = default_left[index] ? left[index] : right[index];
        else
            node = value < split_condition[index] ? left[index] : right[index];
    }}
    return NAN;
}}

static double memtune_xgb_v4_predict_target(const double *features, double base_score,
    const uint32_t *offsets, const int32_t *left, const int32_t *right,
    const int32_t *split_index, const double *split_condition,
    const uint8_t *default_left, const double *leaf_weight)
{{
    double result = base_score;
    uint32_t tree;
    for (tree = 0; tree < 240; ++tree)
        result += memtune_xgb_v4_tree(features, offsets, left, right, split_index,
            split_condition, default_left, leaf_weight, tree);
    return result;
}}

static unsigned long long memtune_xgb_v4_hash_u64(unsigned long long hash,
    unsigned long long value)
{{
    int index;
    for (index = 0; index < 8; ++index) {{
        hash ^= (value >> (index * 8)) & 0xffU;
        hash *= MEMTUNE_FNV_PRIME;
    }}
    return hash;
}}

static int64_t memtune_xgb_v4_leaf_id(double cache_mb, double one_mb, double multi_mb)
{{
    unsigned long long hash = MEMTUNE_FNV_OFFSET;
    unsigned long long bits;
    memcpy(&bits, &cache_mb, sizeof(bits)); hash = memtune_xgb_v4_hash_u64(hash, bits);
    memcpy(&bits, &one_mb, sizeof(bits)); hash = memtune_xgb_v4_hash_u64(hash, bits);
    memcpy(&bits, &multi_mb, sizeof(bits)); hash = memtune_xgb_v4_hash_u64(hash, bits);
    hash &= 0x7fffffffffffffffULL;
    return hash == 0 ? 1 : (int64_t)hash;
}}

void memtune_xgb_v4_features_to_array(const MemTuneWorkMemFeaturesV4 *features,
    double output[MEMTUNE_XGB_V4_FEATURE_COUNT])
{{
    const double values[MEMTUNE_XGB_V4_FEATURE_COUNT] = {{
        features->hash_join_nodes, features->sort_nodes, features->aggregate_nodes,
        features->window_nodes, features->max_plan_rows_log10, features->max_plan_width,
        features->total_cost, features->parallel_workers_planned, features->parallel_aware_nodes,
        features->involved_table_total_size_mb, features->involved_index_total_size_mb,
        features->table_count, features->index_table_ratio, features->total_cost_log1p,
        features->table_size_log1p, features->index_size_log1p, features->rows_width_log1p,
        features->plan_node_count, features->sort_input_rows, features->sort_tuple_width,
        features->sort_input_bytes, features->sort_key_count, features->sort_input_rows_log1p,
        features->sort_input_bytes_log1p
    }};
    int index;
    for (index = 0; index < MEMTUNE_XGB_V4_FEATURE_COUNT; ++index)
        output[index] = isfinite(values[index]) ? values[index] : memtune_xgb_v4_imputation[index];
}}

MemTuneXgbV4Prediction memtune_predict_xgb_v4(const double input[MEMTUNE_XGB_V4_FEATURE_COUNT])
{{
    MemTuneXgbV4Prediction result;
    double cache_raw = memtune_xgb_v4_predict_target(input, memtune_xgb_v4_cache_base_score,
        memtune_xgb_v4_cache_tree_offsets, memtune_xgb_v4_cache_left,
        memtune_xgb_v4_cache_right, memtune_xgb_v4_cache_split_index,
        memtune_xgb_v4_cache_split_condition, memtune_xgb_v4_cache_default_left,
        memtune_xgb_v4_cache_leaf_weight);
    double one_raw = memtune_xgb_v4_predict_target(input, memtune_xgb_v4_one_base_score,
        memtune_xgb_v4_one_tree_offsets, memtune_xgb_v4_one_left,
        memtune_xgb_v4_one_right, memtune_xgb_v4_one_split_index,
        memtune_xgb_v4_one_split_condition, memtune_xgb_v4_one_default_left,
        memtune_xgb_v4_one_leaf_weight);
    result.cache_mb = isfinite(cache_raw) ? fmax(expm1(cache_raw), MEMTUNE_XGB_V4_MIN_MB) : NAN;
    result.one_pass_mb = isfinite(one_raw) ? fmax(expm1(one_raw), MEMTUNE_XGB_V4_MIN_MB) : NAN;
    if (isfinite(result.cache_mb) && isfinite(result.one_pass_mb)) {{
        result.one_pass_mb = fmin(result.one_pass_mb, result.cache_mb);
        result.multi_pass_mb = fmax(MEMTUNE_XGB_V4_MIN_MB,
            result.one_pass_mb - MEMTUNE_XGB_V4_MULTI_PASS_DELTA_MB);
    }} else {{
        result.multi_pass_mb = NAN;
    }}
    result.model_version = MEMTUNE_XGB_V4_MODEL_VERSION;
    result.leaf_id = memtune_xgb_v4_leaf_id(result.cache_mb, result.one_pass_mb,
        result.multi_pass_mb);
    return result;
}}

bool GsWorkmemXgbV4PredictDetail(const double features[MEMTUNE_XGB_V4_FEATURE_COUNT],
    GsAmmDtreeDetail *detail)
{{
    MemTuneXgbV4Prediction prediction;
    double bounds[GS_AMM_DTREE_BOUND_COUNT];
    if (features == NULL || detail == NULL)
        return false;
    prediction = memtune_predict_xgb_v4(features);
    if (!isfinite(prediction.cache_mb) || !isfinite(prediction.one_pass_mb) ||
        !isfinite(prediction.multi_pass_mb) || prediction.cache_mb < prediction.one_pass_mb ||
        prediction.one_pass_mb < prediction.multi_pass_mb)
        return false;
    bounds[0] = prediction.cache_mb; bounds[1] = prediction.one_pass_mb;
    bounds[2] = prediction.multi_pass_mb;
    gs_amm_dtree_detail(bounds, prediction.model_version, prediction.leaf_id, detail);
    return true;
}}
"""
    source = source.replace("V4", f"V{model_version}")
    source = source.replace("v4", f"v{model_version}")
    source = source.replace(
        f"#define MEMTUNE_XGB_V{model_version}_MODEL_VERSION 4",
        f"#define MEMTUNE_XGB_V{model_version}_MODEL_VERSION {model_version}",
    )
    path.write_text(source, encoding="ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--models-dir", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--model-version", type=int, default=4)
    args = parser.parse_args()
    config = json.loads((args.models_dir / "model_config.json").read_text(encoding="utf-8"))
    one_pass_refit = config.get("one_pass_refit")
    if one_pass_refit and not bool((one_pass_refit.get("deployment_gate") or {}).get("passed")):
        raise SystemExit("refusing to export one-pass refit that did not pass its frozen five-stage AP gate")
    if tuple(config.get("feature_names", ())) != FEATURE_NAMES:
        raise SystemExit("model feature order is not the expected mixed_clean schema")
    cache = json.loads((args.models_dir / "cache_mb.json").read_text(encoding="utf-8"))
    one = json.loads((args.models_dir / "one_pass_mb.json").read_text(encoding="utf-8"))
    for model in (cache, one):
        params = model["learner"]["learner_model_param"]
        if int(params["num_feature"]) != len(FEATURE_NAMES):
            raise SystemExit("unexpected model feature count")
        if len(model["learner"]["gradient_booster"]["model"]["trees"]) != 240:
            raise SystemExit("expected exactly 240 trees")
    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.source.parent.mkdir(parents=True, exist_ok=True)
    emit_header(args.header, args.model_version)
    emit_cpp(args.source, cache, one, config, args.model_version)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
